# Generated by Django 5.1.6 on 2025-03-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
